//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FolderSaver {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FolderSaver.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALT.
        /// </summary>
        internal static string ALT {
            get {
                return ResourceManager.GetString("ALT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to config.ini.
        /// </summary>
        internal static string configFile {
            get {
                return ResourceManager.GetString("configFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTRL.
        /// </summary>
        internal static string CTRL {
            get {
                return ResourceManager.GetString("CTRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .zip.
        /// </summary>
        internal static string dotZip {
            get {
                return ResourceManager.GetString("dotZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config file was found but settings could not be loaded.
        /// </summary>
        internal static string FileFoundNoConfig {
            get {
                return ResourceManager.GetString("FileFoundNoConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No backup file found.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey Pressed!.
        /// </summary>
        internal static string HKPressed {
            get {
                return ResourceManager.GetString("HKPressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit: CTRL + SHIFT + Q.
        /// </summary>
        internal static string QuitHotkey {
            get {
                return ResourceManager.GetString("QuitHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit Hotkeys could not be loaded.
        /// </summary>
        internal static string QuitNotloaded {
            get {
                return ResourceManager.GetString("QuitNotloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring from.
        /// </summary>
        internal static string RestoreFrom {
            get {
                return ResourceManager.GetString("RestoreFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore: CTRL + SHIFT + Z.
        /// </summary>
        internal static string RestoreHotkey {
            get {
                return ResourceManager.GetString("RestoreHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Hotkeys could not be loaded.
        /// </summary>
        internal static string RestoreNotloaded {
            get {
                return ResourceManager.GetString("RestoreNotloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save: CTRL + SHIFT + S.
        /// </summary>
        internal static string SaveHotkey {
            get {
                return ResourceManager.GetString("SaveHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Hotkeys could not be loaded.
        /// </summary>
        internal static string SaveNotloaded {
            get {
                return ResourceManager.GetString("SaveNotloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHIFT.
        /// </summary>
        internal static string SHIFT {
            get {
                return ResourceManager.GetString("SHIFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong, default Hotkeys will be used..
        /// </summary>
        internal static string SomethingWrongDefaultHotKey {
            get {
                return ResourceManager.GetString("SomethingWrongDefaultHotKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NBGI.
        /// </summary>
        internal static string SourceFolder {
            get {
                return ResourceManager.GetString("SourceFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NBGI_Backup.
        /// </summary>
        internal static string ZipFolder {
            get {
                return ResourceManager.GetString("ZipFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZipperHotKeyQuit.
        /// </summary>
        internal static string ZipperHKQuit {
            get {
                return ResourceManager.GetString("ZipperHKQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZipperHotKeyRestore.
        /// </summary>
        internal static string ZipperHKRestore {
            get {
                return ResourceManager.GetString("ZipperHKRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZipperHotKey.
        /// </summary>
        internal static string ZipperHKSave {
            get {
                return ResourceManager.GetString("ZipperHKSave", resourceCulture);
            }
        }
    }
}
